### ISSUE TITLE
Split Tabitha up into sub-packages

### ISSUE THREAD

**Issue by twilco** [Widen/tabitha#27]
Currently, if you want to utilize Tabitha's reading/writing capabilities for only a certain file type, you must still bring in the code and dependencies for all other types, too.  If, for example, I know all I want to do is work with XLSX files, it's wasteful for me to have to also pull in the dependencies and whatnot required for CSV processing.

I propose we split Tabitha up into sub-packages, which would allow users to only pull in what they need.  We'd probably need a `tabitha-core` package, and then a sub-package for each major type of tabular data - `tabitha-delimited`, `tabitha-excel`, `tabitha-ods`, etc.

**Comment by sagebind** [comment]
Solved by #30.
